project:
  type: book
  preview: 
    browser: true
    port: 4200
  output-dir: _book

execute: 
  freeze: auto

book:
  title: "Bayesian Data Analysis with Python"
  author: "Robbin Romijnders"
  date: today
  chapters:
    - index.qmd
    - part: "Concepts and Data Analysis"
      chapters:
        - chapters/01_concepts_and_data_analysis/01_01_intro.qmd
        - chapters/01_concepts_and_data_analysis/01_02_basics_of_probability.qmd
        - chapters/01_concepts_and_data_analysis/01_03_frequentist_inference.qmd
        - chapters/01_concepts_and_data_analysis/01_04_tossing_a_coin.qmd
    - summary.qmd
    - references.qmd
  appendices: 
    - chapters/appendices/binary_variable.qmd
    - chapters/appendices/continuous_variable.qmd  

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  # pdf:
  #   documentclass: scrreprt



