project:
  type: book
  preview: 
    browser: true
    port: 4200
  output-dir: _book

execute: 
  freeze: auto

book:
  title: "Bayesian Data Analysis with Python"
  author: "Robbin Romijnders"
  date: today
  chapters:
    - index.qmd
    - chapters/01_concepts_and_data_analysis/01_01_intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  # pdf:
  #   documentclass: scrreprt



